### ISSUE TITLE
 Can't get attribute 'DetectionModel' on <module 'models.yolo' from '/content/yolov5/yolov5_prune/models/yolo.py'>

### ISSUE THREAD

**Issue by seungyong0313** [uyzhang/yolov5_prune#6]
what's the error?

Traceback (most recent call last):
  File "prune.py", line 223, in <module>
    main()
  File "prune.py", line 209, in main
    prune(**params_prune)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "prune.py", line 85, in prune
    model = DetectMultiBackend(weights, device=device, dnn=dnn, fuse=False)
  File "/content/yolov5/yolov5_prune/models/common.py", line 308, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, map_location=device, fuse=fuse)
  File "/content/yolov5/yolov5_prune/models/experimental.py", line 96, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location=map_location)  # load
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 1049, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 1042, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'DetectionModel' on <module 'models.yolo' from '/content/yolov5/yolov5_prune/models/yolo.py'>

**Comment by uyzhang** [comment]
What is your command to run?

**Comment by dungviet112** [comment]
@uyzhang Hi. I have a similar issue when using your prune with this command:
python prune.py --percent 0.3 --weights ../yolov5/runs/train/results_90epochs/weights/last.pt --data ../Detection/fire-smoke-dfs-final/data.yaml --cfg models/yolov5s.yaml --imgsz 640
Can you check this fault, please
![image](https://user-images.githubusercontent.com/72445774/215382430-f552e7dd-7526-4231-9580-89f471d29f6c.png)
